//source: https://medium.com/flutter-community/multilingual-flutter-the-easy-way-52e4b182d6e9

final Map<String, Map<String, String>> localizedValues = {
  'af': {
    'current': 'Huidig ',
    'forecast': 'Voorspelling ',
    'locations': 'Liggings ',
    'more': 'Meer ',
    'feelsLike': 'Voel soos ',
    'wind': 'Wind ',
    'sunrise': 'Sonsopkoms ',
    'sunset': 'Sonsondergang ',
    'humidity': 'Vogtigheid ',
    'pressure': 'Druk ',
    'currentLocationTitle': 'Huidige ligging ',
    'weatherRadar': 'Weer Radar ',
    'weatherRadarAboutTitle': 'Oor Weather Radar ',
    'weatherRadarAboutBody':
        "Pluvia Weather se 'Weer Radar' gebruik 'n 'openweerthermap' webblad. Dit ondersteun die besigtiging van neerslag, druk, temperatuur, windspoed en wolkvoorspellings wêreldwyd. Dit kan lei tot hoër dataverbruik. ",
    'lastUpdatedAt': 'Laaste opgedateer by ',
    'locationDisabledPrompt':
        'Vir Pluvia weer om weer in jou huidige ligging te wys, aktiveer plek. ',
    'darkMode': 'Donker af ',
    'useFahrenheit': 'Gebruik Fahrenheit ',
    'refreshToSee': 'Herlaai om veranderinge te sien ',
    'windSpeedUnit': 'Windspoed-eenheid ',
    'aboutPluvia': 'Oor Pluvia Weer ',
    'viewOnGithub': 'Bekyk Pluvia weer op Github ',
    'localTime': 'Plaaslike tyd ',
    'loading': 'Laai ',
    'chooseLocationToView': "Kies 'n plek om weer te sien. ",
    'openLocationSettings': 'Open Plek instellings ',
    'close': 'Naby ',
    'retry': 'Probeer weer ',
    'serverErrorTitle': 'Bedienerprobleem ',
    'serverErrorBody':
        'Pluvia weer kon nie data kry nie. Die OpenWeatherMap-bedieners kan af wees. ',
    'networkErrorText':
        'Aktiveer asseblief WiFi of mobiele data en probeer weer ',
    'gettingLocationMessage': 'Kry plek ... '
  },
  'ar': {
    'current': 'تيار ',
    'forecast': 'تنبؤ بالمناخ ',
    'locations': 'المواقع ',
    'more': 'أكثر ',
    'feelsLike': 'أحس كأنني ',
    'wind': 'ريح ',
    'sunrise': 'شروق الشمس ',
    'sunset': 'غروب الشمس ',
    'humidity': 'رطوبة ',
    'pressure': 'ضغط ',
    'currentLocationTitle': 'الموقع الحالي ',
    'weatherRadar': 'رادار الطقس ',
    'weatherRadarAboutTitle': 'حول رادار الطقس ',
    'weatherRadarAboutBody':
        'يستخدم "رادار الطقس" لطقس الطقس في Pluvia صفحة ويب "OpenWeathermap". وهو يدعم عرض هطول الأمطار والضغط ودرجة الحرارة وسرعة الرياح والتوقعات السحابية على مستوى العالم. قد يؤدي هذا إلى ارتفاع استخدام البيانات. ',
    'lastUpdatedAt': 'آخر تحديث في ',
    'locationDisabledPrompt':
        'ل Pluvia الطقس لإظهار الطقس في موقعك الحالي، تمكين الموقع. ',
    'darkMode': 'الوضع المظلم ',
    'useFahrenheit': 'استخدام فهرنهايت ',
    'refreshToSee': 'تحديث لمعرفة التغييرات ',
    'windSpeedUnit': 'وحدة سرعة الرياح ',
    'aboutPluvia': 'حول Pluvia الطقس ',
    'viewOnGithub': 'عرض Pluvia الطقس على جيثب ',
    'localTime': 'الوقت المحلي ',
    'loading': 'جار التحميل ',
    'chooseLocationToView': 'اختر موقعا لعرض الطقس. ',
    'openLocationSettings': 'إعدادات الموقع المفتوح ',
    'close': 'يغلق ',
    'retry': 'أعد ',
    'serverErrorTitle': 'خطأ في الخادم ',
    'serverErrorBody':
        'لم يستطع طقس Pluvia الحصول على البيانات. قد تكون خوادم OpenWeathermap أسفل. ',
    'networkErrorText':
        'يرجى تمكين البيانات واي فاي أو المحمولة وإعادة المحاولة ',
    'gettingLocationMessage': 'الحصول على الموقع ... '
  },
  'az': {
    'current': 'Cərəyan ',
    'forecast': 'Proqnozlaşdırmaq ',
    'locations': 'Yer ',
    'more': 'Daha çox ',
    'feelsLike': 'Kimi hiss edir ',
    'wind': 'Külək ',
    'sunrise': 'Günəşin doğuşu ',
    'sunset': 'Qürub ',
    'humidity': 'Rütubət ',
    'pressure': 'Təzyiq etmək ',
    'currentLocationTitle': 'Hazırki yer ',
    'weatherRadar': 'Hava radarları ',
    'weatherRadarAboutTitle': 'Hava radarı haqqında ',
    'weatherRadarAboutBody':
        "Pluvia Hava '' Hava Radar '' Openweathermap 'veb səhifəsini istifadə edir. Yağış, təzyiq, temperatur, külək sürətini və qlobal miqyasda bulud proqnozlarına baxmağı dəstəkləyir. Bu, daha yüksək məlumat istifadəsinə səbəb ola bilər. ",
    'lastUpdatedAt': 'Son yeniləndi ',
    'locationDisabledPrompt':
        'Pluviya hava şəraiti cari yerinizdə havanın göstərilməsi, yeri aktivləşdirin. ',
    'darkMode': 'Tündlük rejimi ',
    'useFahrenheit': 'Fahrenheit istifadə edin ',
    'refreshToSee': 'Dəyişiklikləri görmək üçün yeniləyin ',
    'windSpeedUnit': 'Külək sürət vahidi ',
    'aboutPluvia': 'Pluvia Hava haqqında ',
    'viewOnGithub': 'Github-da Pluvia Hava baxın ',
    'localTime': 'Yerli vaxt ',
    'loading': 'Yükləmə ',
    'chooseLocationToView': 'Hava baxmaq üçün bir yer seçin. ',
    'openLocationSettings': 'Yer parametrlərini açın ',
    'close': 'Yaxın ',
    'retry': 'Yenidən cəhd etmək ',
    'serverErrorTitle': 'Server səhvi ',
    'serverErrorBody':
        'Pluvia Hava Məlumat əldə edə bilmədi. OpenWeatherMap serverləri aşağı ola bilər. ',
    'networkErrorText':
        'Zəhmət olmasa WiFi və ya mobil məlumatları aktivləşdirin və yenidən cəhd edin ',
    'gettingLocationMessage': 'Yer almaq ... '
  },
  'bg': {
    'current': 'Текущ ',
    'forecast': 'Прогноза ',
    'locations': 'Места ',
    'more': '| Повече ▼ ',
    'feelsLike': 'Се чувства като ',
    'wind': 'Вятър ',
    'sunrise': 'Изгрев ',
    'sunset': 'Сънсет ',
    'humidity': 'Влажност ',
    'pressure': 'Натиск ',
    'currentLocationTitle': 'Настоящо местонахождение ',
    'weatherRadar': 'Времето Радар ',
    'weatherRadarAboutTitle': 'За метеорологичен радар ',
    'weatherRadarAboutBody':
        'Pluvia Weather\'s \'Radar\' използва уеб страницата на "OpenWeathermap". Той поддържа преглеждане на валежи, налягане, температура, скорост на вятъра и облачни прогнози в световен мащаб. Това може да доведе до по-висока употреба на данни. ',
    'lastUpdatedAt': 'Последно актуализирано в ',
    'locationDisabledPrompt':
        'За Pluvia времето за показване на времето в текущото си местоположение, разрешаване на местоположението. ',
    'darkMode': 'Тъмен режим ',
    'useFahrenheit': 'Използвайте Fahrenheit. ',
    'refreshToSee': 'Обновяване, за да видите промените ',
    'windSpeedUnit': 'Единица за скорост на вятъра ',
    'aboutPluvia': 'За Плувия Време ',
    'viewOnGithub': 'Виж Плувия Времето в Github ',
    'localTime': 'Местно време ',
    'loading': 'Зареждане ',
    'chooseLocationToView': 'Изберете място, за да видите времето. ',
    'openLocationSettings': 'Настройки за откриване на местоположение ',
    'close': 'Близо ',
    'retry': 'Повторен опит ',
    'serverErrorTitle': 'грешка в сървъра ',
    'serverErrorBody':
        'Плувия времето не можеше да получи данни. Сървърите на OpenWeathermap могат да бъдат намалени. ',
    'networkErrorText':
        'Моля, активирайте WiFi или мобилни данни и опитайте отново ',
    'gettingLocationMessage': 'Получаване на местоположение ... '
  },
  'ca': {
    'current': 'Habitual ',
    'forecast': 'Pronòstic ',
    'locations': 'Localitzacions ',
    'more': 'Més ',
    'feelsLike': 'Se sent com ',
    'wind': 'Vent ',
    'sunrise': 'Sortida de sol ',
    'sunset': 'Posta de sol ',
    'humidity': 'Humitat ',
    'pressure': 'Pressió ',
    'currentLocationTitle': 'Localització actual ',
    'weatherRadar': 'Radar meteorològic ',
    'weatherRadarAboutTitle': 'Sobre el radar meteorològic ',
    'weatherRadarAboutBody':
        "'El radar meteorològic del temps de Pluvia' utilitza una pàgina web 'OpenWeatherMap'. Admet la visualització de la precipitació, la pressió, la temperatura, la velocitat del vent i les previsions del núvol a nivell mundial. Això pot provocar un ús superior de dades. ",
    'lastUpdatedAt': 'Darrera actualització a ',
    'locationDisabledPrompt':
        'Per a Plutuvia, per mostrar el clima a la vostra ubicació actual, habiliteu la ubicació. ',
    'darkMode': 'Mode fosc ',
    'useFahrenheit': 'Utilitzar fahrenheit ',
    'refreshToSee': 'Actualitzeu per veure els canvis ',
    'windSpeedUnit': 'Unitat de velocitat del vent ',
    'aboutPluvia': 'Sobre pluvia ',
    'viewOnGithub': 'Consulteu el temps de pluvia a github ',
    'localTime': 'Hora local ',
    'loading': 'Carregar ',
    'chooseLocationToView': 'Trieu una ubicació per veure el clima. ',
    'openLocationSettings': 'Configuració de la ubicació oberta ',
    'close': 'Tanca ',
    'retry': 'Tornar a provar ',
    'serverErrorTitle': 'Error del servidor ',
    'serverErrorBody':
        'El temps de pluvia no va poder obtenir dades. Pot ser que els servidors de lamentador OpenWeath. ',
    'networkErrorText': 'Activeu dades WiFi o mòbil i torneu-ho a provar ',
    'gettingLocationMessage': 'Obtenir ubicació ... '
  },
  'cs': {
    'current': 'Proud ',
    'forecast': 'Předpověď ',
    'locations': 'Umístění ',
    'more': 'Více ',
    'feelsLike': 'Cítí jako ',
    'wind': 'Vítr ',
    'sunrise': 'svítání ',
    'sunset': 'Západ slunce ',
    'humidity': 'Vlhkost vzduchu ',
    'pressure': 'Tlak ',
    'currentLocationTitle': 'Současná pozice ',
    'weatherRadar': 'Počasí radar ',
    'weatherRadarAboutTitle': 'O počasí radar ',
    'weatherRadarAboutBody':
        'PEVUVIA Počasí \'Počasí radar\' používá webovou stránku "Openweathermap". Podporuje prohlížení srážení, tlaku, teploty, rychlosti větru a předpovědi mraků po celém světě. To může vést k vyššímu využití dat. ',
    'lastUpdatedAt': 'Naposledy aktualizováno ',
    'locationDisabledPrompt':
        'Pro počasí pluvia zobrazilo počasí ve své aktuální poloze, povolte umístění. ',
    'darkMode': 'Tmavý režim ',
    'useFahrenheit': 'Použijte Fahrenheit. ',
    'refreshToSee': 'Obnovit se zobrazí změny ',
    'windSpeedUnit': 'Jednotka rychlosti větru ',
    'aboutPluvia': 'O PLUVIA Počasí ',
    'viewOnGithub': 'Zobrazit Pluvia Počasí na GitHub ',
    'localTime': 'Místní čas ',
    'loading': 'načítání ',
    'chooseLocationToView': 'Vyberte si místo pro zobrazení počasí. ',
    'openLocationSettings': 'Nastavení otevřeného místa ',
    'close': 'Zavřít ',
    'retry': 'Opakovat se ',
    'serverErrorTitle': 'Chyba serveru ',
    'serverErrorBody':
        'Počasí Pluvia nemohlo získat data. Servery OpenWeatherap mohou být dole. ',
    'networkErrorText': 'Zapněte WiFi nebo mobilní data a opakujte ',
    'gettingLocationMessage': 'Získání umístění ... '
  },
  'da': {
    'current': 'Nuværende ',
    'forecast': 'Vejrudsigt ',
    'locations': 'Placeringer ',
    'more': 'Mere ',
    'feelsLike': 'Føles som ',
    'wind': 'Vind ',
    'sunrise': 'Solopgang ',
    'sunset': 'Solnedgang ',
    'humidity': 'Fugtighed ',
    'pressure': 'Tryk ',
    'currentLocationTitle': 'Nuværende lokation ',
    'weatherRadar': 'Vejrradar ',
    'weatherRadarAboutTitle': 'Om vejrradar ',
    'weatherRadarAboutBody':
        "Pluvia Vejret 'Vejrradar' bruger en 'Openweathap' webside. Det understøtter visning af nedbør, tryk, temperatur, vindhastighed og skyprognoser globalt. Dette kan føre til højere dataforbrug. ",
    'lastUpdatedAt': 'Sidst opdateret på ',
    'locationDisabledPrompt':
        'For Pluvia vejr for at vise vejret i din nuværende placering, aktiver placering. ',
    'darkMode': 'Mørk tilstand ',
    'useFahrenheit': 'Brug Fahrenheit. ',
    'refreshToSee': 'Opdater for at se ændringer ',
    'windSpeedUnit': 'Vindhastighedsenhed ',
    'aboutPluvia': 'Om Pluvia Weather ',
    'viewOnGithub': 'Se Pluvia Vejret på Github ',
    'localTime': 'Lokal tid ',
    'loading': 'Indlæser ',
    'chooseLocationToView': 'Vælg et sted for at se vejret. ',
    'openLocationSettings': 'Åbn placeringsindstillinger. ',
    'close': 'Tæt ',
    'retry': 'Prøve igen ',
    'serverErrorTitle': 'Server Fejl ',
    'serverErrorBody':
        'Pluvia vejr kunne ikke få data. Openweathermap-servere kan være nede. ',
    'networkErrorText': 'Aktivér wifi eller mobile data og prøv igen ',
    'gettingLocationMessage': 'Få beliggenhed ... '
  },
  'de': {
    'current': 'Strom ',
    'forecast': 'Prognose ',
    'locations': 'Standorte ',
    'more': 'Mehr ',
    'feelsLike': 'Fühlt sich an wie ',
    'wind': 'Wind ',
    'sunrise': 'Sonnenaufgang ',
    'sunset': 'Sonnenuntergang ',
    'humidity': 'Feuchtigkeit ',
    'pressure': 'Druck ',
    'currentLocationTitle': 'Aktueller Standort ',
    'weatherRadar': 'Wetterradar. ',
    'weatherRadarAboutTitle': 'Über das Wetterradar. ',
    'weatherRadarAboutBody':
        "Das Wetter Radar von Pluvia Weather 'verwendet eine' OpenWeathermap 'Webseite. Es unterstützt das Betrachten von Niederschlag, Druck, Temperatur, Windgeschwindigkeit und Cloud-Prognosen weltweit. Dies kann zu einer höheren Datennutzung führen. ",
    'lastUpdatedAt': 'Zuletzt aktualisiert at. ',
    'locationDisabledPrompt':
        'Für das Wetter von Pluvia, um Wetter in Ihrem aktuellen Standort anzuzeigen, aktivieren Sie den Standort. ',
    'darkMode': 'Dunkler Modus ',
    'useFahrenheit': 'Verwenden Sie Fahrenheit ',
    'refreshToSee': 'Aktualisieren, um Änderungen anzuzeigen ',
    'windSpeedUnit': 'Windgeschwindigkeitseinheit ',
    'aboutPluvia': 'Über Pluvia Wetter ',
    'viewOnGithub': 'Sehen Sie sich Pluvia Wetter auf Github an ',
    'localTime': 'Ortszeit ',
    'loading': 'Wird geladen ',
    'chooseLocationToView': 'Wählen Sie einen Ort, um das Wetter anzuzeigen. ',
    'openLocationSettings': 'Offene Standorteinstellungen ',
    'close': 'Schließen ',
    'retry': 'Wiederholen ',
    'serverErrorTitle': 'Serverfehler ',
    'serverErrorBody':
        'Das Wetter von Pluvia konnte keine Daten erhalten. Die OpenWeatsMap-Server können unten sein. ',
    'networkErrorText':
        'Bitte aktivieren Sie WIFI- oder Mobilfunkdaten und versuchen Sie es erneut ',
    'gettingLocationMessage': 'Lage ... '
  },
  'el': {
    'current': 'Ρεύμα ',
    'forecast': 'Πρόβλεψη ',
    'locations': 'Θέσεις ',
    'more': 'Περισσότερο ',
    'feelsLike': 'Αισθάνεται σαν ',
    'wind': 'Ανεμος ',
    'sunrise': 'Ανατολή ηλίου ',
    'sunset': 'Η δυση του ηλιου ',
    'humidity': 'Υγρασία ',
    'pressure': 'Πίεση ',
    'currentLocationTitle': 'Τωρινή τοποθεσία ',
    'weatherRadar': 'Ραντάρ καιρού ',
    'weatherRadarAboutTitle': 'Σχετικά με τον καιρό ραντάρ ',
    'weatherRadarAboutBody':
        'Το "καιρό ραντάρ" του Pluvia "χρησιμοποιεί μια ιστοσελίδα" openweathermap ". Υποστηρίζει την προβολή βροχόπτωσης, πίεσης, θερμοκρασίας, ταχύτητας ανέμου και πρόβλεψης σύννεφων σε παγκόσμιο επίπεδο. Αυτό μπορεί να οδηγήσει σε υψηλότερη χρήση δεδομένων. ',
    'lastUpdatedAt': 'Τελευταία ενημέρωση στο ',
    'locationDisabledPrompt':
        'Για τον καιρό Pluvia για να εμφανιστεί καιρός στην τρέχουσα τοποθεσία σας, ενεργοποιήστε την τοποθεσία. ',
    'darkMode': 'Σκοτεινή λειτουργία ',
    'useFahrenheit': 'Χρησιμοποιήστε το Fahrenheit ',
    'refreshToSee': 'Ανανέωση για να δείτε αλλαγές ',
    'windSpeedUnit': 'Μονάδα ταχύτητας ανέμου ',
    'aboutPluvia': 'Σχετικά με τον καιρό Pluvia ',
    'viewOnGithub': 'Δείτε τον καιρό Pluvia στο github ',
    'localTime': 'Τοπική ώρα ',
    'loading': 'Φόρτωση ',
    'chooseLocationToView':
        'Επιλέξτε μια τοποθεσία για να δείτε τις καιρικές συνθήκες. ',
    'openLocationSettings': 'Ανοίξτε τις ρυθμίσεις θέσης ',
    'close': 'Κλείσε ',
    'retry': 'Προσπαθησε ξανα ',
    'serverErrorTitle': 'Σφάλμα Διακομιστή ',
    'serverErrorBody':
        'Ο καιρός στο Pluvia δεν μπορούσε να πάρει δεδομένα. Οι διακομιστές openweathermap μπορεί να είναι κάτω. ',
    'networkErrorText':
        'Ενεργοποιήστε το WiFi ή τα κινητά δεδομένα και δοκιμάστε ξανά ',
    'gettingLocationMessage': 'Λήψη της τοποθεσίας ... '
  },
  'en': {
    'current': 'Current ',
    'forecast': 'Forecast ',
    'locations': 'Locations ',
    'more': 'More ',
    'feelsLike': 'Feels like ',
    'wind': 'Wind ',
    'sunrise': 'Sunrise ',
    'sunset': 'Sunset ',
    'humidity': 'Humidity ',
    'pressure': 'Pressure ',
    'currentLocationTitle': 'Current Location ',
    'weatherRadar': 'Weather Radar ',
    'weatherRadarAboutTitle': 'About Weather Radar ',
    'weatherRadarAboutBody':
        "Pluvia Weather's 'Weather Radar' uses an 'OpenWeatherMap' webpage. It supports viewing Precipitation, Pressure, Temperature, Wind Speed and Cloud forecasts globally. This may lead to higher data usage. ",
    'lastUpdatedAt': 'Last updated at ',
    'locationDisabledPrompt':
        'For Pluvia Weather to show weather in your current location, enable location. ',
    'darkMode': 'Dark Mode ',
    'useFahrenheit': 'Use Fahrenheit ',
    'refreshToSee': 'Refresh to see changes ',
    'windSpeedUnit': 'Wind Speed Unit ',
    'aboutPluvia': 'About Pluvia Weather ',
    'viewOnGithub': 'View Pluvia Weather on Github ',
    'localTime': 'Local Time ',
    'loading': 'Loading ',
    'chooseLocationToView': 'Choose a location to view weather. ',
    'openLocationSettings': 'Open Location Settings ',
    'close': 'Close ',
    'retry': 'Retry ',
    'serverErrorTitle': 'Server Error ',
    'serverErrorBody':
        'Pluvia Weather could not get data. The OpenWeatherMap servers may be down. ',
    'networkErrorText': 'Please enable WIFI or Mobile Data and retry ',
    'gettingLocationMessage': 'Getting location... '
  },
  'es': {
    'current': 'Actual ',
    'forecast': 'Pronóstico ',
    'locations': 'Ubicaciones ',
    'more': 'Más ',
    'feelsLike': 'Se siente como ',
    'wind': 'Viento ',
    'sunrise': 'Amanecer ',
    'sunset': 'Atardecer ',
    'humidity': 'Humedad ',
    'pressure': 'Presión ',
    'currentLocationTitle': 'Ubicación actual ',
    'weatherRadar': 'Radar meteorológico ',
    'weatherRadarAboutTitle': 'Sobre el radar del tiempo ',
    'weatherRadarAboutBody':
        "El 'Radar meteorológico' del clima de Pluvia usa una página web 'OpenWeatherMap'. Admite la visualización de la precipitación, la presión, la temperatura, la velocidad del viento y las previsiones en la nube a nivel mundial. Esto puede llevar a un mayor uso de datos. ",
    'lastUpdatedAt': 'Última actualización en ',
    'locationDisabledPrompt':
        'Para el clima de Pluvia para mostrar el clima en su ubicación actual, habilitar la ubicación. ',
    'darkMode': 'Modo oscuro ',
    'useFahrenheit': 'Usa Fahrenheit ',
    'refreshToSee': 'Actualizar para ver los cambios. ',
    'windSpeedUnit': 'Unidad de velocidad del viento ',
    'aboutPluvia': 'Sobre el clima de Pluvia ',
    'viewOnGithub': 'Ver el clima de Pluvia en GitHub ',
    'localTime': 'Hora local ',
    'loading': 'Cargando ',
    'chooseLocationToView': 'Elija una ubicación para ver el clima. ',
    'openLocationSettings': 'Configuración de ubicación abierta ',
    'close': 'Cerca ',
    'retry': 'Rever ',
    'serverErrorTitle': 'Error del Servidor ',
    'serverErrorBody':
        'El clima de Pluvia no pudo obtener datos. Los servidores OpenWeatherMap pueden estar bajando. ',
    'networkErrorText':
        'Por favor, habilite los datos wifi o móviles y vuelva a intentarlo ',
    'gettingLocationMessage': 'Obtención de ubicación ... '
  },
  'eu': {
    'current': 'Korronte ',
    'forecast': 'Iragarpen ',
    'locations': 'Kokapen ',
    'more': 'Gehiago ',
    'feelsLike': 'Gustatzen zait ',
    'wind': 'Harilkatu ',
    'sunrise': 'Argi-urratze ',
    'sunset': 'Ilunsenti ',
    'humidity': 'Ezkotasun ',
    'pressure': 'Presio ',
    'currentLocationTitle': 'Egungo kokapena ',
    'weatherRadar': 'Eguraldi radarra ',
    'weatherRadarAboutTitle': 'Eguraldi Radar buruz ',
    'weatherRadarAboutBody':
        "Pluvia Eguraldiaren 'Eguraldi Radar' 'OpenWeatherMap' web orria erabiltzen du. Prezipitazioa, presioa, tenperatura, haizearen abiadura eta hodeiko aurreikuspenak ikustea onartzen du. Horrek datu-erabilera handiagoa izan dezake. ",
    'lastUpdatedAt': 'Azken eguneraketa ',
    'locationDisabledPrompt':
        'Pluvia eguraldiak zure uneko kokapenean eguraldia erakusteko, gaitu kokapena. ',
    'darkMode': 'Modu iluna ',
    'useFahrenheit': 'Erabili fahrenheit ',
    'refreshToSee': 'Freskatu aldaketak ikusteko ',
    'windSpeedUnit': 'Haizearen abiadura unitatea ',
    'aboutPluvia': 'Pluvia Eguraldiari buruz ',
    'viewOnGithub': 'Ikusi Pluvia Eguraldia GitHub-en ',
    'localTime': 'Bertako ordua ',
    'loading': 'Kargatzen ',
    'chooseLocationToView': 'Aukeratu kokapen bat eguraldia ikusteko. ',
    'openLocationSettings': 'Kokapen irekiko ezarpenak ',
    'close': 'Hurbileko ',
    'retry': 'Berrirohartu ',
    'serverErrorTitle': 'Zerbitzariaren errorea ',
    'serverErrorBody':
        'PLUVIA Eguraldiak ezin izan ditu datuak jaso. Openweathermap zerbitzariak behera egin ahal izango dira. ',
    'networkErrorText':
        'Mesedez, gaitu WiFi edo Mugikorreko datuak eta saiatu berriro ',
    'gettingLocationMessage': 'Kokapena lortzea ... '
  },
  'fa': {
    'current': 'جاری ',
    'forecast': 'پیش بینی ',
    'locations': 'مکان ها ',
    'more': 'بیشتر ',
    'feelsLike': 'احساس می کنم ',
    'wind': 'باد ',
    'sunrise': 'طلوع خورشید ',
    'sunset': 'غروب خورشید ',
    'humidity': 'رطوبت ',
    'pressure': 'فشار ',
    'currentLocationTitle': 'موقعیت فعلی ',
    'weatherRadar': 'رادار آب و هوا ',
    'weatherRadarAboutTitle': 'درباره رادار آب و هوا ',
    'weatherRadarAboutBody':
        '"رادار آب و هوا" Pluvia "از صفحه وب" OpenWeathermaP "استفاده می کند. این پشتیبانی از مشاهده بارش، فشار، دما، سرعت باد و پیش بینی های ابر در سطح جهانی پشتیبانی می کند. این ممکن است منجر به استفاده از داده های بالاتر شود. ',
    'lastUpdatedAt': 'آخرین به روز رسانی در ',
    'locationDisabledPrompt':
        'برای PLUVIA آب و هوا برای نشان دادن آب و هوا در مکان فعلی خود، محل را فعال کنید. ',
    'darkMode': 'حالت تاریک ',
    'useFahrenheit': 'از fahrenheit استفاده کنید ',
    'refreshToSee': 'تازه کردن برای دیدن تغییرات ',
    'windSpeedUnit': 'واحد سرعت باد ',
    'aboutPluvia': 'درباره Pluvia آب و هوا ',
    'viewOnGithub': 'مشاهده آب و هوا Pluvia در Github ',
    'localTime': 'زمان محلی ',
    'loading': 'بارگذاری ',
    'chooseLocationToView': 'یک مکان برای مشاهده آب و هوا را انتخاب کنید. ',
    'openLocationSettings': 'تنظیمات مکان باز ',
    'close': 'نزدیک ',
    'retry': 'دوباره امتحان کنید ',
    'serverErrorTitle': 'خطای سرور ',
    'serverErrorBody':
        'آب و هوا PLUVIA نمی تواند اطلاعات را دریافت کند. سرورهای OpenWeathermap ممکن است پایین باشند. ',
    'networkErrorText':
        'لطفا داده های WiFi یا تلفن همراه را فعال کنید و دوباره امتحان کنید ',
    'gettingLocationMessage': 'گرفتن محل ... '
  },
  'fi': {
    'current': 'Nykyinen ',
    'forecast': 'Ennuste ',
    'locations': 'Sijainnit ',
    'more': 'Lisää ',
    'feelsLike': 'Tuntuu siltä ',
    'wind': 'Tuuli ',
    'sunrise': 'Auringonnousu ',
    'sunset': 'Auringonlasku ',
    'humidity': 'Kosteus ',
    'pressure': 'Paine ',
    'currentLocationTitle': 'Tämänhetkinen olinpaikka ',
    'weatherRadar': 'Sää tutka ',
    'weatherRadarAboutTitle': 'Tietoja säätutka ',
    'weatherRadarAboutBody':
        'Pluvian sää Radar "käyttää" OpenWeatherMap "-verkkosivua. Se tukee sademäärän, paineen, lämpötilan, tuulen nopeuden ja pilviennusteiden katselua maailmanlaajuisesti. Tämä voi johtaa suurempaan tietojen käyttöön. ',
    'lastUpdatedAt': 'Päivitetty viimeksi ',
    'locationDisabledPrompt':
        'Pluvia Sää näyttää sää nykyisessä sijainnissa, mahdollista sijainti. ',
    'darkMode': 'Tumma tila ',
    'useFahrenheit': 'Käytä Fahrenheit ',
    'refreshToSee': 'Päivitä muutoksia ',
    'windSpeedUnit': 'Tuulenopeusyksikkö ',
    'aboutPluvia': 'Tietoja Pluvian sää ',
    'viewOnGithub': 'Näytä putkia Sää Github ',
    'localTime': 'Paikallinen aika ',
    'loading': 'Ladataan ',
    'chooseLocationToView': 'Valitse sijainti säästä. ',
    'openLocationSettings': 'Avaa sijaintiasetukset ',
    'close': 'kiinni ',
    'retry': 'Yrittää uudelleen ',
    'serverErrorTitle': 'palvelinvirhe ',
    'serverErrorBody':
        'Pluvian sää ei voinut saada tietoja. OpenWeatherMap-palvelimet voivat olla alas. ',
    'networkErrorText':
        'Ota käyttöön WiFi- tai mobiilidata ja yritä uudelleen ',
    'gettingLocationMessage': 'Sijainnin saaminen ... '
  },
  'fr': {
    'current': 'Actuelle',
    'forecast': 'Prévoir ',
    'locations': 'Emplacements ',
    'more': 'Suite ',
    'feelsLike': 'Se sent comme ',
    'wind': 'Vent ',
    'sunrise': 'lever du soleil ',
    'sunset': 'Coucher de soleil ',
    'humidity': 'Humidité ',
    'pressure': 'Pression ',
    'currentLocationTitle': 'Localisation actuelle ',
    'weatherRadar': 'Radar météorologique ',
    'weatherRadarAboutTitle': 'Sur le radar météo ',
    'weatherRadarAboutBody':
        'Le «radar météo» de Pluvia »utilise une page Web« OpenWeatherMap ». Il prend en charge la visualisation des précipitations, la pression, la température, la vitesse du vent et les prévisions de nuage dans le monde. Cela peut conduire à une utilisation plus élevée des données. ',
    'lastUpdatedAt': 'Dernière mise à jour à ',
    'locationDisabledPrompt':
        "Pour la météo Pluvia pour afficher la météo dans votre position actuelle, activez l'emplacement. ",
    'darkMode': 'Mode sombre ',
    'useFahrenheit': 'Utilisez Fahrenheit ',
    'refreshToSee': 'Actualiser pour voir les changements ',
    'windSpeedUnit': 'Unité de vitesse du vent ',
    'aboutPluvia': 'À propos de Pluvia Météo ',
    'viewOnGithub': 'Voir Pluvia Météo sur Github ',
    'localTime': 'Heure locale ',
    'loading': 'Chargement ',
    'chooseLocationToView': 'Choisissez un endroit pour voir la météo. ',
    'openLocationSettings': "Paramètres d'emplacement ouvert ",
    'close': 'Fermer ',
    'retry': 'Réessayez ',
    'serverErrorTitle': 'erreur du serveur ',
    'serverErrorBody':
        "Le temps de Pluvia n'a pas pu obtenir de données. Les serveurs OpenWeatherMap peuvent être en panne. ",
    'networkErrorText':
        'Veuillez activer WiFi ou des données mobiles et réessayer ',
    'gettingLocationMessage': "Obtenir l'emplacement ... "
  },
  'gl': {
    'current': 'Current. ',
    'forecast': 'Previsión ',
    'locations': 'Localizacións ',
    'more': 'Máis ',
    'feelsLike': 'Séntese like. ',
    'wind': 'Vento ',
    'sunrise': 'Sunrise. ',
    'sunset': 'Sunset. ',
    'humidity': 'Humidade ',
    'pressure': 'Presión ',
    'currentLocationTitle': 'Localización actual ',
    'weatherRadar': 'Radar meteorolóxico. ',
    'weatherRadarAboutTitle': 'Sobre o radar meteorolóxico. ',
    'weatherRadarAboutBody':
        "PLUVIA Weather's 'Weather Radar' usa unha páxina web de 'OpenWeatherMap'. Soporta visualización de precipitación, presión, temperatura, velocidade de vento e previsións de nube globalmente. Isto pode levar a un maior uso de datos. ",
    'lastUpdatedAt': 'Última actualización actualizada ',
    'locationDisabledPrompt':
        'Para o clima de Pluvia para mostrar o tempo na súa localización actual, habilita a localización. ',
    'darkMode': 'Modo escuro ',
    'useFahrenheit': 'Use Fahrenheit. ',
    'refreshToSee': 'Actualizar para ver cambios ',
    'windSpeedUnit': 'Unidade de velocidade do vento ',
    'aboutPluvia': 'Sobre Pluvia Weather. ',
    'viewOnGithub': 'Ver o clima de pluvia en GitHub ',
    'localTime': 'Tempo local ',
    'loading': 'Cargando ',
    'chooseLocationToView': 'Escolla unha localización para ver o tempo. ',
    'openLocationSettings': 'Abre a configuración de localización ',
    'close': 'Preto ',
    'retry': 'Retry. ',
    'serverErrorTitle': 'Erro do servidor ',
    'serverErrorBody':
        'O clima de Pluvia non puido obter datos. Os servidores de OpenWeatherMap poden estar abaixo. ',
    'networkErrorText':
        'Por favor, active WiFi ou datos móbiles e ténteo de novo ',
    'gettingLocationMessage': 'Obtendo a localización ... '
  },
  'he': {
    'current': 'נוֹכְחִי ',
    'forecast': 'תַחֲזִית ',
    'locations': 'מיקומים ',
    'more': 'יותר ',
    'feelsLike': 'מרגיש כמו ',
    'wind': 'רוּחַ ',
    'sunrise': 'זריחה ',
    'sunset': 'שקיעת השמש ',
    'humidity': 'לחות ',
    'pressure': 'לַחַץ ',
    'currentLocationTitle': 'מיקום נוכחי ',
    'weatherRadar': 'מכ"ם מזג אויר ',
    'weatherRadarAboutTitle': 'על מכ"ם מזג אוויר ',
    'weatherRadarAboutBody':
        "Pluvia מזג האוויר 'מזג האוויר' משתמש בדף אינטרנט 'Openweathermap'. הוא תומך בעקיפת משקעים, לחץ, טמפרטורה, מהירות הרוח ותחזיות ענן ברחבי העולם. הדבר עלול להוביל לשימוש בנתונים גבוהים יותר. ",
    'lastUpdatedAt': 'עודכן לאחרונה ',
    'locationDisabledPrompt':
        'עבור מזג האוויר Pluvia להצגת מזג האוויר במיקום הנוכחי שלך, הפעל מיקום. ',
    'darkMode': 'מצב כהה ',
    'useFahrenheit': 'השתמש fahrenheit ',
    'refreshToSee': 'רענון לראות שינויים ',
    'windSpeedUnit': 'יחידת מהירות הרוח ',
    'aboutPluvia': 'על מזג האוויר בפלאוויה ',
    'viewOnGithub': 'הצג את מזג האוויר Pluvia על Github ',
    'localTime': 'זמן מקומי ',
    'loading': 'טוען ',
    'chooseLocationToView': 'בחר מיקום כדי להציג את מזג האוויר. ',
    'openLocationSettings': 'הגדרות מיקום פתוחות ',
    'close': 'סגור ',
    'retry': 'נסה שוב ',
    'serverErrorTitle': 'שגיאת שרת ',
    'serverErrorBody':
        'מזג האוויר Pluvia לא יכול לקבל נתונים. שרתי Openweathermap עשוי להיות למטה. ',
    'networkErrorText': 'הפעל את WiFi או נתונים ניידים ונסה שוב ',
    'gettingLocationMessage': 'קבלת מיקום ... '
  },
  'hi': {
    'current': 'वर्तमान ',
    'forecast': 'इस तरह का अनुभव ',
    'locations': 'स्थानों ',
    'more': 'अधिक ',
    'feelsLike': 'की तरह लगना ',
    'wind': 'हवा ',
    'sunrise': 'सूर्योदय ',
    'sunset': 'सूर्य का अस्त होना ',
    'humidity': 'नमी ',
    'pressure': 'दबाव ',
    'currentLocationTitle': 'वर्तमान स्थान ',
    'weatherRadar': 'मौसम रडार ',
    'weatherRadarAboutTitle': 'मौसम रडार के बारे में ',
    'weatherRadarAboutBody':
        "प्लुविया मौसम का 'मौसम रडार' एक 'ओपनवेथर्मैप' वेबपृष्ठ का उपयोग करता है। यह वैश्विक स्तर पर वर्षा, दबाव, तापमान, हवा की गति और बादल पूर्वानुमान देखने का समर्थन करता है। इससे उच्च डेटा उपयोग हो सकता है। ",
    'lastUpdatedAt': 'अंतिम बार अपडेट किया गया ',
    'locationDisabledPrompt':
        'प्लुविया के लिए मौसम आपके वर्तमान स्थान में मौसम दिखाने के लिए, स्थान सक्षम करें। ',
    'darkMode': 'डार्क मोड ',
    'useFahrenheit': 'फारेनहाइट का उपयोग करें ',
    'refreshToSee': 'परिवर्तन देखने के लिए ताज़ा करें ',
    'windSpeedUnit': 'पवन गति इकाई ',
    'aboutPluvia': 'प्लुविया मौसम के बारे में ',
    'viewOnGithub': 'Github पर प्लुविया का मौसम देखें ',
    'localTime': 'स्थानीय समय ',
    'loading': 'लोड हो रहा है ',
    'chooseLocationToView': 'मौसम देखने के लिए एक स्थान चुनें। ',
    'openLocationSettings': 'स्थान सेटिंग्स खोलें ',
    'close': 'बंद करे ',
    'retry': 'पुन: प्रयास करें ',
    'serverErrorTitle': 'सर्वर त्रुटि ',
    'serverErrorBody':
        'प्लुविया मौसम डेटा नहीं मिला। OpenWeatherMap सर्वर नीचे हो सकते हैं। ',
    'networkErrorText':
        'कृपया वाईफाई या मोबाइल डेटा सक्षम करें और पुनः प्रयास करें ',
    'gettingLocationMessage': 'स्थान प्राप्त करना ... '
  },
  'hr': {
    'current': 'Trenutno ',
    'forecast': 'Prognoza ',
    'locations': 'Lokacije ',
    'more': 'Više ',
    'feelsLike': 'Čini se kao ',
    'wind': 'Vjetar ',
    'sunrise': 'Izlazak sunca ',
    'sunset': 'Zalazak sunca ',
    'humidity': 'Vlažnost ',
    'pressure': 'Pritisak ',
    'currentLocationTitle': 'Trenutna lokacija ',
    'weatherRadar': 'Vremenski radar ',
    'weatherRadarAboutTitle': 'O vremenskim radaru ',
    'weatherRadarAboutBody':
        "Pluvia Weather's 'Weather Radar' koristi web stranicu 'OpenWeatherMap'. Podržava pregledavanje oborina, tlaka, temperature, brzine vjetra i prognoze oblaka na globalnoj razini. To može dovesti do viših korištenja podataka. ",
    'lastUpdatedAt': 'Zadnje ažurirano na ',
    'locationDisabledPrompt':
        'Za vrijeme Pluvia za prikaz vremena na trenutnom mjestu, omogućite lokaciju. ',
    'darkMode': 'Taman način rada ',
    'useFahrenheit': 'Koristite Fahrenheit ',
    'refreshToSee': 'Osvježiti vidjeti promjene ',
    'windSpeedUnit': 'Jedinica za brzinu vjetra ',
    'aboutPluvia': 'O Vrijeme Pluvia ',
    'viewOnGithub': 'Pogledajte vrijeme Pluvia na Github ',
    'localTime': 'Lokalno vrijeme ',
    'loading': 'Učitavam ',
    'chooseLocationToView': 'Odaberite mjesto za pregled vremena. ',
    'openLocationSettings': 'Postavke otvorene lokacije ',
    'close': 'Zatvoriti ',
    'retry': 'Ponovo pokušati ',
    'serverErrorTitle': 'pogreška servera ',
    'serverErrorBody':
        'Vrijeme Pluvia nije moglo dobiti podatke. OpenWeatherMap poslužitelji mogu biti dolje. ',
    'networkErrorText':
        'Omogućite WiFi ili mobilne podatke i pokušajte ponovo ',
    'gettingLocationMessage': 'Dobivanje lokacije ... '
  },
  'hu': {
    'current': 'Jelenlegi ',
    'forecast': 'Előrejelzés ',
    'locations': 'Helyszínek ',
    'more': 'Több ',
    'feelsLike': 'Olyan, mintha ',
    'wind': 'Szél ',
    'sunrise': 'Napkelte ',
    'sunset': 'Napnyugta ',
    'humidity': 'páratartalom ',
    'pressure': 'Nyomás ',
    'currentLocationTitle': 'Jelenlegi tartózkodási hely ',
    'weatherRadar': 'Időjárási radar ',
    'weatherRadarAboutTitle': 'Az időjárási radarról ',
    'weatherRadarAboutBody':
        'A Pluvia időjárás "időjárási radar" egy "Openweathermap" weboldalt használ. Támogatja a csapadékot, a nyomást, a hőmérsékletet, a szélsebességet és a felhő előrejelzést világszerte. Ez magasabb adathasználathoz vezethet. ',
    'lastUpdatedAt': 'Utolsó frissítés ',
    'locationDisabledPrompt':
        'A Pluvia időjárás esetén az időjárás megjelenítése az aktuális helyen, engedélyezze a helyét. ',
    'darkMode': 'Sötét mód ',
    'useFahrenheit': 'Használja a fahrenheit használatát ',
    'refreshToSee': 'Frissítse a változtatásokat ',
    'windSpeedUnit': 'Szélsebesség-egység ',
    'aboutPluvia': 'A Pluvia időjáról ',
    'viewOnGithub': 'View Pluvia időjárás a Githubon ',
    'localTime': 'Helyi idő ',
    'loading': 'Betöltés ',
    'chooseLocationToView':
        'Válasszon egy helyet az időjárás megtekintéséhez. ',
    'openLocationSettings': 'Nyílt helybeállítások ',
    'close': 'Bezárás ',
    'retry': 'Próbálja újra ',
    'serverErrorTitle': 'szerver hiba ',
    'serverErrorBody':
        'A Pluvia időjárás nem tudott adatokat kapni. Az OpenWeathermap szerverek leállhatnak. ',
    'networkErrorText':
        'Kérjük, engedélyezze a WiFi-t vagy a mobil adatokat, és próbálja újra ',
    'gettingLocationMessage': 'Helymeghatározás ... '
  },
  'id': {
    'current': 'Arus ',
    'forecast': 'Ramalan cuaca ',
    'locations': 'Lokasi ',
    'more': 'Lebih ',
    'feelsLike': 'Terasa seperti ',
    'wind': 'Angin ',
    'sunrise': 'Matahari terbit ',
    'sunset': 'Matahari terbenam ',
    'humidity': 'Kelembaban ',
    'pressure': 'Tekanan ',
    'currentLocationTitle': 'Lokasi saat ini ',
    'weatherRadar': 'Radar cuaca ',
    'weatherRadarAboutTitle': 'Tentang Cuaca Radar ',
    'weatherRadarAboutBody':
        "'Radar cuaca' Cuaca Pluvia menggunakan halaman web 'Openweathermap'. Ini mendukung tampilan pengendapan, tekanan, suhu, kecepatan angin, dan ramalan awan secara global. Ini dapat menyebabkan penggunaan data yang lebih tinggi. ",
    'lastUpdatedAt': 'Terakhir Diperbarui pada. ',
    'locationDisabledPrompt':
        'Untuk cuaca Pluvia untuk menunjukkan cuaca di lokasi Anda saat ini, aktifkan lokasi. ',
    'darkMode': 'Mode gelap ',
    'useFahrenheit': 'Gunakan Fahrenheit. ',
    'refreshToSee': 'Refresh untuk melihat perubahan ',
    'windSpeedUnit': 'Unit Kecepatan Angin ',
    'aboutPluvia': 'Tentang cuaca Pluvia. ',
    'viewOnGithub': 'Lihat Cuaca Pluvia di GitHub ',
    'localTime': 'Waktu lokal ',
    'loading': 'Memuat ',
    'chooseLocationToView': 'Pilih lokasi untuk melihat cuaca. ',
    'openLocationSettings': 'Buka Pengaturan Lokasi .. ',
    'close': 'Menutup ',
    'retry': 'Mencoba kembali ',
    'serverErrorTitle': 'server error ',
    'serverErrorBody':
        'Cuaca pluvia tidak dapat memperoleh data. Server OpenWeathermap mungkin turun. ',
    'networkErrorText': 'Harap aktifkan WiFi atau data seluler dan coba lagi ',
    'gettingLocationMessage': 'Mendapatkan lokasi ... '
  },
  'it': {
    'current': 'attuale ',
    'forecast': 'Previsione ',
    'locations': 'Posizioni ',
    'more': 'Di più ',
    'feelsLike': 'Si sente come ',
    'wind': 'Vento ',
    'sunrise': 'Alba ',
    'sunset': 'Tramonto ',
    'humidity': 'Umidità ',
    'pressure': 'Pressione ',
    'currentLocationTitle': 'Posizione attuale ',
    'weatherRadar': 'Radar meteorologico ',
    'weatherRadarAboutTitle': 'Sul radar meteorologico ',
    'weatherRadarAboutBody':
        'Il "radar meteorologico di Pluvia Weather utilizza una pagina web" OpenWeatherMermap ". Supporta la visualizzazione di precipitazioni, pressione, temperatura, velocità del vento e previsioni cloud globalmente. Ciò può portare a un maggiore utilizzo dei dati. ',
    'lastUpdatedAt': 'Ultimo aggiornamento a. ',
    'locationDisabledPrompt':
        'Per il tempo PLUVIA per mostrare tempo nella posizione corrente, abilitare la posizione. ',
    'darkMode': 'Modalità scura ',
    'useFahrenheit': 'Usa Fahrenheit. ',
    'refreshToSee': 'Aggiorna per vedere le modifiche ',
    'windSpeedUnit': 'Unità di velocità del vento ',
    'aboutPluvia': 'Informazioni su Pluvia Meteo ',
    'viewOnGithub': 'Visualizza il tempo Pluvia su GitHub ',
    'localTime': 'Ora locale ',
    'loading': 'Caricamento in corso ',
    'chooseLocationToView': 'Scegli una posizione per visualizzare il tempo. ',
    'openLocationSettings': 'Aprire le impostazioni della posizione ',
    'close': 'Vicino',
    'retry': 'Ricercare ',
    'serverErrorTitle': 'Errore del server ',
    'serverErrorBody':
        'Il tempo del PLUVIA non ha potuto ottenere dati. I server OpenWeatherMermap potrebbero essere giù. ',
    'networkErrorText': 'Si prega di abilitare WiFi o dati mobili e riprovare ',
    'gettingLocationMessage': 'Ottenere la posizione ... '
  },
  'ja': {
    'current': '電流 ',
    'forecast': 'for ',
    'locations': '居場所 ',
    'more': 'もっと ',
    'feelsLike': 'のように感じている ',
    'wind': '風 ',
    'sunrise': '日の出 ',
    'sunset': '日没 ',
    'humidity': '湿気 ',
    'pressure': '圧力 ',
    'currentLocationTitle': '現在位置 ',
    'weatherRadar': '天気レーダー ',
    'weatherRadarAboutTitle': '天気レーダーについて ',
    'weatherRadarAboutBody':
        'Pluvia天気の「天気レーダー」は「OpenWeatherMap」のウェブページを使用しています。 それは降水量、圧力、温度、風速、そしてクラウドの予測を世界的に見ることをサポートしています。 これにより、データの使用が高くなる可能性があります。 ',
    'lastUpdatedAt': '最後に更新されました ',
    'locationDisabledPrompt': '現在地の天気を表示するにはPluvia天気のために、場所を有効にしてください。 ',
    'darkMode': '暗いモード ',
    'useFahrenheit': '華氏の使用 ',
    'refreshToSee': '変更を見るために更新されます ',
    'windSpeedUnit': '風速ユニット ',
    'aboutPluvia': 'プルビアの天候について ',
    'viewOnGithub': 'Githubのプルビアの天気を見る ',
    'localTime': '現地時間 ',
    'loading': '荷重 ',
    'chooseLocationToView': '天気を見る場所を選択してください。 ',
    'openLocationSettings': '開いた場所の設定 ',
    'close': '閉じる ',
    'retry': 'リトライ ',
    'serverErrorTitle': 'サーバーエラー ',
    'serverErrorBody':
        'プルビアの天気はデータを取得できませんでした。 OpenWeatherMapサーバーがダウンしている可能性があります。 ',
    'networkErrorText': 'WiFiまたはモバイルデータを有効にして再試行してください ',
    'gettingLocationMessage': '場所を取得する... '
  },
  'ko': {
    'current': '흐름 ',
    'forecast': '예보 ',
    'locations': '위치 ',
    'more': '더 ',
    'feelsLike': '같은 느낌 ',
    'wind': '바람 ',
    'sunrise': '해돋이 ',
    'sunset': '일몰 ',
    'humidity': '습기 ',
    'pressure': '압력 ',
    'currentLocationTitle': '현재 위치 ',
    'weatherRadar': '날씨 레이더 ',
    'weatherRadarAboutTitle': '날씨 레이더에 대하여 ',
    'weatherRadarAboutBody':
        "Pluvia 날씨의 '날씨 레이더'는 'OpenWeatherMap'웹 페이지를 사용합니다. 전 세계적으로 강수량, 압력, 온도, 풍속 및 클라우드 예측을 볼 수 있습니다. 이로 인해 데이터 사용이 높을 수 있습니다. ",
    'lastUpdatedAt': '마지막으로 업데이트되었습니다 ',
    'locationDisabledPrompt': 'Pluvia 날씨의 경우 현재 위치의 날씨를 보여주기 위해 위치를 활성화하십시오. ',
    'darkMode': '어두운 모드 ',
    'useFahrenheit': '화씨를 사용하십시오 ',
    'refreshToSee': '새로 고침하여 변경 사항을 확인하십시오 ',
    'windSpeedUnit': '풍속 단위 ',
    'aboutPluvia': 'Pluvia About About Pluvia ',
    'viewOnGithub': 'Github에서 Pluvia 날씨를 봅니다 ',
    'localTime': '현지 시각 ',
    'loading': '로딩 ',
    'chooseLocationToView': '날씨를 볼 위치를 선택하십시오. ',
    'openLocationSettings': '열린 위치 설정 ',
    'close': '닫기 ',
    'retry': '다시 해 보다 ',
    'serverErrorTitle': '서버 오류 ',
    'serverErrorBody':
        'Pluvia 날씨는 데이터를 얻을 수 없습니다. OpenWeatherMAP 서버가 다운 될 수 있습니다. ',
    'networkErrorText': 'Wi-Fi 또는 모바일 데이터를 활성화하고 재시도하십시오 ',
    'gettingLocationMessage': '위치 점점 ... '
  },
  'lt': {
    'current': 'Dabartinis ',
    'forecast': 'Prognozė ',
    'locations': 'Vietos. \\ T ',
    'more': 'Daugiau. ',
    'feelsLike': 'Jaučiasi ',
    'wind': 'Vėjas ',
    'sunrise': 'Saulėtekis ',
    'sunset': 'Saulėlydis ',
    'humidity': 'Drėgmė ',
    'pressure': 'Slėgis. \\ T ',
    'currentLocationTitle': 'Dabartinė vieta ',
    'weatherRadar': 'Orų radaras ',
    'weatherRadarAboutTitle': 'Apie orų radarą ',
    'weatherRadarAboutBody':
        '"Plyuvia Oro" orų radaras "naudoja" OpenWeatherm "tinklalapį. Jis palaiko kritulių, slėgio, temperatūros, vėjo greičio ir debesų prognozes visame pasaulyje. Tai gali sukelti didesnį duomenų naudojimą. ',
    'lastUpdatedAt': 'Paskutinį kartą atnaujinta adresu ',
    'locationDisabledPrompt':
        '"Pluvia Oras" pasirodys orai dabartinėje vietoje, įjungti vietą. ',
    'darkMode': 'Tamsus režimas ',
    'useFahrenheit': 'Naudokite Fahrenheit. ',
    'refreshToSee': 'Atnaujinkite, kad pamatytumėte pakeitimus ',
    'windSpeedUnit': 'Vėjo greičio vienetas ',
    'aboutPluvia': 'Apie "Pluvia Oras" ',
    'viewOnGithub': 'Peržiūrėti "Pluvia Oras Github ',
    'localTime': 'Vietinis laikas ',
    'loading': 'Pakrovimas ',
    'chooseLocationToView':
        'Pasirinkite vietą, kurioje norite peržiūrėti orą. ',
    'openLocationSettings': 'Atidarykite vietos nustatymus ',
    'close': 'Uždaryti ',
    'retry': 'Pakartokite ',
    'serverErrorTitle': 'serverio klaida ',
    'serverErrorBody':
        'Pluvia oras negalėjo gauti duomenų. "OpenWeathermap" serveriai gali būti žemyn. ',
    'networkErrorText':
        'Įgalinkite "WiFi" arba "Mobile" duomenis ir bandykite dar kartą ',
    'gettingLocationMessage': 'Gauti vietą ... '
  },
  'lv': {
    'current': 'Strāva ',
    'forecast': 'Prognoze ',
    'locations': 'Atrašanās vietas ',
    'more': 'Vairāk ',
    'feelsLike': 'Jūtas kā ',
    'wind': 'Vējš ',
    'sunrise': 'Saullēkts ',
    'sunset': 'Saulriets ',
    'humidity': 'Mitrums ',
    'pressure': 'Spiediens ',
    'currentLocationTitle': 'Pašreizējā atrašanās vieta ',
    'weatherRadar': 'Laika radars ',
    'weatherRadarAboutTitle': 'Par laika radaru ',
    'weatherRadarAboutBody':
        'Pluvia Laika apstākļu "Laika radars" izmanto tīmekļa lapu "OpenweVermap". Tā atbalsta nokrišņu, spiediena, temperatūras, vēja ātruma un mākonis prognozes visā pasaulē. Tas var novest pie augstākas datu izmantošanas. ',
    'lastUpdatedAt': 'Pēdējo reizi atjaunināts ',
    'locationDisabledPrompt':
        'Pluvia Laiks parādīt laika apstākļus pašreizējā vietā, iespējojiet atrašanās vietu. ',
    'darkMode': 'Tumšs režīms ',
    'useFahrenheit': 'Izmantot Fārenheita ',
    'refreshToSee': 'Atsvaidzināt, lai redzētu izmaiņas ',
    'windSpeedUnit': 'Vēja ātruma vienība ',
    'aboutPluvia': 'Par Pluvia Laiks ',
    'viewOnGithub': 'Skatīt Pluvia Laiks Github ',
    'localTime': 'Vietējais laiks ',
    'loading': 'Iekraušana ',
    'chooseLocationToView': 'Izvēlieties vietu, lai skatītu laika apstākļus. ',
    'openLocationSettings': 'Atvērtā atrašanās vietas iestatījumi ',
    'close': 'Tuvoties ',
    'retry': 'Atkārtot ',
    'serverErrorTitle': 'servera kļūda ',
    'serverErrorBody':
        'Pluvia Laiks nevarēja iegūt datus. OpenWermap serveri var būt uz leju. ',
    'networkErrorText':
        'Lūdzu, iespējojiet wifi vai mobilos datus un mēģiniet vēlreiz ',
    'gettingLocationMessage': 'Atrašanās vietas iegūšana ... '
  },
  'mk': {
    'current': 'Струја ',
    'forecast': 'Прогноза ',
    'locations': 'Локации ',
    'more': 'Повеќе ',
    'feelsLike': 'Се чувствува како ',
    'wind': 'Ветер ',
    'sunrise': 'Изгрејсонце ',
    'sunset': 'Зајдисонце ',
    'humidity': 'Влажност ',
    'pressure': 'Притисок ',
    'currentLocationTitle': 'Моментална локација ',
    'weatherRadar': 'Времето Радар ',
    'weatherRadarAboutTitle': 'За временски радар ',
    'weatherRadarAboutBody':
        'Времето радарски радар на Pluvia Weather користи веб-страница на OpenWANTEMPAP. Поддржува гледање на врнежи, притисок, температура, брзина на ветерот и прогнозите на облак на глобално ниво. Ова може да доведе до повисока употреба на податоци. ',
    'lastUpdatedAt': 'Последно освежено ',
    'locationDisabledPrompt':
        'За Pluvia времето за да го покажете времето на вашата моментална локација, овозможете локација. ',
    'darkMode': 'Темно режим ',
    'useFahrenheit': 'Користете Фаренхајт ',
    'refreshToSee': 'Освежи за да ги видите промените ',
    'windSpeedUnit': 'Единица за брзина на ветерот ',
    'aboutPluvia': 'За Pluvia Weather ',
    'viewOnGithub': 'Погледнете го времето на Pluvia на GitHub ',
    'localTime': 'Локално време ',
    'loading': 'Вчитување ',
    'chooseLocationToView': 'Изберете локација за да ги видите времето. ',
    'openLocationSettings': 'Отворете ги поставките за локација ',
    'close': 'Затвори ',
    'retry': 'Повторете ',
    'serverErrorTitle': 'грешка во серверот ',
    'serverErrorBody':
        'Времето Pluvia не можеше да добие податоци. Серверите за отворен сервери може да бидат долу. ',
    'networkErrorText':
        'Ве молиме вклучете WiFi или мобилни податоци и обидете се повторно ',
    'gettingLocationMessage': 'Добивање локација ... '
  },
  'nl': {
    'current': 'Actueel ',
    'forecast': 'Voorspelling ',
    'locations': 'Locaties ',
    'more': 'Meer ',
    'feelsLike': 'Voelt als ',
    'wind': 'Wind ',
    'sunrise': 'zonsopkomst ',
    'sunset': 'Zonsondergang ',
    'humidity': 'Vochtigheid ',
    'pressure': 'Druk ',
    'currentLocationTitle': 'Huidige locatie ',
    'weatherRadar': 'Weerradar ',
    'weatherRadarAboutTitle': 'Over weerradar ',
    'weatherRadarAboutBody':
        "Het 'weerradar' van Pluvia 'maakt gebruik van een webpagina' OpenWATERMAP '. Het ondersteunt het bekijken van precipitatie, druk, temperatuur, windsnelheid en cloudprognoses wereldwijd. Dit kan leiden tot een hoger gegevensgebruik. ",
    'lastUpdatedAt': 'Laatst bijgewerkt op ',
    'locationDisabledPrompt':
        'Voor het weer om weer weer te geven op uw huidige locatie, de locatie inschakelen. ',
    'darkMode': 'Donkere modus ',
    'useFahrenheit': 'Gebruik Fahrenheit ',
    'refreshToSee': 'Vernieuwen om wijzigingen te zien ',
    'windSpeedUnit': 'Windsnelheid-eenheid ',
    'aboutPluvia': 'Over PLUVIA Weer ',
    'viewOnGithub': 'Bekijk het weer van Pluvia op Github ',
    'localTime': 'Lokale tijd ',
    'loading': 'Bezig met laden ',
    'chooseLocationToView': 'Kies een locatie om het weer te bekijken. ',
    'openLocationSettings': 'Open locatie-instellingen ',
    'close': 'Dichtbij ',
    'retry': 'Opnieuw proberen ',
    'serverErrorTitle': 'Serverfout ',
    'serverErrorBody':
        'Het weer van Pluvia kon geen gegevens ontvangen. De OpenWeathermap-servers kunnen dalen. ',
    'networkErrorText':
        'Schakel WiFi of mobiele gegevens in en probeer het opnieuw ',
    'gettingLocationMessage': 'Locatie krijgen ... '
  },
  'no': {
    'current': 'Nåværende ',
    'forecast': 'Prognose ',
    'locations': 'Steder ',
    'more': 'Mer ',
    'feelsLike': 'Føles som ',
    'wind': 'Vind ',
    'sunrise': 'Soloppgang ',
    'sunset': 'Solnedgang ',
    'humidity': 'Luftfuktighet ',
    'pressure': 'Press ',
    'currentLocationTitle': 'Nåværende plassering ',
    'weatherRadar': 'Vær Radar ',
    'weatherRadarAboutTitle': 'Om værradar ',
    'weatherRadarAboutBody':
        "Pluvia Værets 'Weather Radar' bruker en 'Openweathmap' nettside. Den støtter å se nedbør, trykk, temperatur, vindhastighet og skyprognoser globalt. Dette kan føre til høyere databruk. ",
    'lastUpdatedAt': 'Sist oppdatert på ',
    'locationDisabledPrompt':
        'For pluvia været for å vise været i din nåværende beliggenhet, aktivere plassering. ',
    'darkMode': 'Mørk modus ',
    'useFahrenheit': 'Bruk Fahrenheit. ',
    'refreshToSee': 'Oppdatere for å se endringer ',
    'windSpeedUnit': 'Vindhastighetsenhet ',
    'aboutPluvia': 'Om pluvia været ',
    'viewOnGithub': 'Se pluvia vær på github ',
    'localTime': 'Lokal tid ',
    'loading': 'Lasting ',
    'chooseLocationToView': 'Velg et sted for å se været. ',
    'openLocationSettings': 'Åpne plasseringsinnstillinger ',
    'close': 'Lukk ',
    'retry': 'Prøv på nytt ',
    'serverErrorTitle': 'serverfeil ',
    'serverErrorBody':
        'Pluvia været kunne ikke få data. Openweathmap-serverne kan være nede. ',
    'networkErrorText':
        'Vennligst aktiver WiFi eller Mobile Data og prøv på nytt ',
    'gettingLocationMessage': 'Få plassering ... '
  },
  'pl': {
    'current': 'obecny ',
    'forecast': 'Prognoza ',
    'locations': 'Lokalizacje ',
    'more': 'Jeszcze ',
    'feelsLike': 'Czuje się jak ',
    'wind': 'Wiatr ',
    'sunrise': 'wschód słońca ',
    'sunset': 'Zachód słońca ',
    'humidity': 'Wilgotność ',
    'pressure': 'Nacisk ',
    'currentLocationTitle': 'Aktualna lokalizacja ',
    'weatherRadar': 'Radar pogodowy. ',
    'weatherRadarAboutTitle': 'O radaru pogodowym. ',
    'weatherRadarAboutBody':
        'Pluvia Pogoda "Radar Pogoda" używa strony internetowej "OpenWeathermap". Obsługuje przeglądanie opadów, ciśnienia, temperatury, prędkości wiatru i prognoz na całym świecie. Może to prowadzić do wyższego wykorzystania danych. ',
    'lastUpdatedAt': 'Ostatnio zaktualizowany at ',
    'locationDisabledPrompt':
        'W przypadku pogody Pluvia pokazuje pogodę w bieżącej lokalizacji, włącz lokalizację. ',
    'darkMode': 'Ciemny tryb ',
    'useFahrenheit': 'Użyj Fahrenheita ',
    'refreshToSee': 'Odśwież, aby zobaczyć zmiany ',
    'windSpeedUnit': 'Jednostka prędkości wiatru. ',
    'aboutPluvia': 'O pogodzie Pluvia. ',
    'viewOnGithub': 'Zobacz Pluvia Pogoda na Github ',
    'localTime': 'Czas lokalny ',
    'loading': 'Ładowanie ',
    'chooseLocationToView': 'Wybierz lokalizację, aby zobaczyć pogodę. ',
    'openLocationSettings': 'Otwórz ustawienia lokalizacji ',
    'close': 'Blisko ',
    'retry': 'Spróbować ponownie ',
    'serverErrorTitle': 'błąd serwera ',
    'serverErrorBody':
        'Pogoda Pluvia nie mogła uzyskać danych. Serwery OpenWeathermap mogą być w dół. ',
    'networkErrorText': 'Włącz wifi lub dane mobilne i ponów próbę ',
    'gettingLocationMessage': 'Uzyskiwanie lokalizacji ... '
  },
  'pt': {
    'current': 'Atual ',
    'forecast': 'Previsão ',
    'locations': 'Localizações ',
    'more': 'Mais ',
    'feelsLike': 'Parece ',
    'wind': 'Vento ',
    'sunrise': 'nascer do sol ',
    'sunset': 'Pôr do sol ',
    'humidity': 'Umidade ',
    'pressure': 'Pressão ',
    'currentLocationTitle': 'Localização atual ',
    'weatherRadar': 'Radar meteorológico ',
    'weatherRadarAboutTitle': 'Sobre o radar meteorológico ',
    'weatherRadarAboutBody':
        'O "radar de tempo" do clavia do tempo usa uma página de \'openweathermap\'. Suporta visualização de precipitação, pressão, temperatura, velocidade do vento e previsões em nuvem globalmente. Isso pode levar a um maior uso de dados. ',
    'lastUpdatedAt': 'Última atualização em. ',
    'locationDisabledPrompt':
        'Para o tempo de pluviia para mostrar o tempo em sua localização atual, ative a localização. ',
    'darkMode': 'Modo escuro ',
    'useFahrenheit': 'Use Fahrenheit ',
    'refreshToSee': 'Atualizar para ver as alterações ',
    'windSpeedUnit': 'Unidade de velocidade do vento. ',
    'aboutPluvia': 'Sobre o tempo de pluvi ',
    'viewOnGithub': 'Ver o tempo de pluviia no github ',
    'localTime': 'Horário local ',
    'loading': 'Carregando ',
    'chooseLocationToView': 'Escolha um local para ver o tempo. ',
    'openLocationSettings': 'Configurações de localização aberta ',
    'close': 'Perto ',
    'retry': 'Repetir ',
    'serverErrorTitle': 'erro de servidor ',
    'serverErrorBody':
        'O tempo de Pluvi não pôde obter dados. Os servidores OpenWeathermap podem estar baixos. ',
    'networkErrorText':
        'Por favor, ative o WiFi ou os dados móveis e tente novamente ',
    'gettingLocationMessage': 'Obtendo localização ... '
  },
  'ro': {
    'current': 'Actual ',
    'forecast': 'Prognoza ',
    'locations': 'Locații ',
    'more': 'Mai mult ',
    'feelsLike': 'Se simte ca ',
    'wind': 'Vânt ',
    'sunrise': 'răsărit ',
    'sunset': 'Apus de soare ',
    'humidity': 'Umiditate ',
    'pressure': 'Presiune ',
    'currentLocationTitle': 'Locatia curenta ',
    'weatherRadar': 'Radar de vreme ',
    'weatherRadarAboutTitle': 'Despre vremea radar ',
    'weatherRadarAboutBody':
        '"Radarul Meteo" al lui Pluvia utilizează o pagină web "OpenWeatherMap". Acesta susține precipitațiile, presiunea, temperatura, viteza vântului și prognozele cloud la nivel global. Acest lucru poate duce la o utilizare mai mare a datelor. ',
    'lastUpdatedAt': 'Ultima actualizare la. ',
    'locationDisabledPrompt':
        'Pentru vremea pluvia pentru a arăta vremea în locația dvs. curentă, activați locația. ',
    'darkMode': 'Modul întunecat. ',
    'useFahrenheit': 'Utilizați Fahrenheit. ',
    'refreshToSee': 'Reîmprospătați pentru a vedea modificările ',
    'windSpeedUnit': 'Viteza vântului ',
    'aboutPluvia': 'Despre vremea Pluvia ',
    'viewOnGithub': 'Vizualizați vremea pluvia pe GitHub ',
    'localTime': 'Ora locala ',
    'loading': 'Se încarcă ',
    'chooseLocationToView': 'Alegeți o locație pentru a vedea vremea. ',
    'openLocationSettings': 'Deschideți setările locației ',
    'close': 'Închide ',
    'retry': 'Reîncercați ',
    'serverErrorTitle': 'Eroare de server ',
    'serverErrorBody':
        'Vremea pluvia nu a putut obține date. Serverele OpenWeatherMap pot fi în jos. ',
    'networkErrorText': 'Activați datele WiFi sau Mobile și Reîncercați ',
    'gettingLocationMessage': 'Obținerea locației ... '
  },
  'ru': {
    'current': 'Текущий ',
    'forecast': 'Прогноз ',
    'locations': 'Локации ',
    'more': 'Более ',
    'feelsLike': 'Как будто ',
    'wind': 'Ветер ',
    'sunrise': 'Восход ',
    'sunset': 'Закат ',
    'humidity': 'Влажность ',
    'pressure': 'Давление ',
    'currentLocationTitle': 'Текущее местоположение ',
    'weatherRadar': 'Радар погоды ',
    'weatherRadarAboutTitle': 'О погоде радар ',
    'weatherRadarAboutBody':
        '«Погода в погоде в плювии» использует веб-страницу «OpenWeatherMap». Он поддерживает просмотр осадков, давления, температуры, скорости ветра и облако прогнозы глобально. Это может привести к более высоким использованию данных. ',
    'lastUpdatedAt': 'Последнее обновление ',
    'locationDisabledPrompt':
        'Погода в плювии показать погоду в вашем текущем местоположении, включить местонахождение. ',
    'darkMode': 'Темный режим ',
    'useFahrenheit': 'Используйте Фаренгейт ',
    'refreshToSee': 'Обновить, чтобы увидеть изменения ',
    'windSpeedUnit': 'Установка скорости ветра ',
    'aboutPluvia': 'О Плювии погода ',
    'viewOnGithub': 'Просмотр погоды в плювии на Github ',
    'localTime': 'Местное время ',
    'loading': 'Загрузка ',
    'chooseLocationToView': 'Выберите место для просмотра погоды. ',
    'openLocationSettings': 'Открытые настройки местоположения ',
    'close': 'Закрывать ',
    'retry': 'Повторение ',
    'serverErrorTitle': 'Ошибка сервера ',
    'serverErrorBody':
        'Погода в плювии не удалось получить данные. Серверы OpenWeatherMap могут быть вниз. ',
    'networkErrorText':
        'Пожалуйста, включите Wi-Fi или мобильные данные и повторите попытку ',
    'gettingLocationMessage': 'Получение местоположения ... '
  },
  'sk': {
    'current': 'Prúd ',
    'forecast': 'Prognóza ',
    'locations': 'Lokality ',
    'more': 'Viac ',
    'feelsLike': 'Pripadá mi to ako ',
    'wind': 'Vetrovať ',
    'sunrise': 'svitanie ',
    'sunset': 'Západ slnka ',
    'humidity': 'Vlhkosť ',
    'pressure': 'Tlak ',
    'currentLocationTitle': 'Súčasná poloha ',
    'weatherRadar': 'Radiar počasia ',
    'weatherRadarAboutTitle': 'O radare počasia ',
    'weatherRadarAboutBody':
        "Pluvia Počasie 'Počasie Radar' používa webovú stránku 'OpenWeatherMap'. Podporuje prezeranie zrážok, tlaku, teploty, rýchlosti vetra a prognózy oblaku globálne. To môže viesť k vyššiemu využívaniu údajov. ",
    'lastUpdatedAt': 'Posledná aktualizácia ',
    'locationDisabledPrompt':
        'Pre PLUVIA Počasie ukázať počasie na vašu aktuálnu polohu, povoľte umiestnenie. ',
    'darkMode': 'Temný režim ',
    'useFahrenheit': 'Používať Fahrenheita ',
    'refreshToSee': 'Obnoviť zmeny ',
    'windSpeedUnit': 'Jednotka pre rýchlosť vetra ',
    'aboutPluvia': 'O Pluvia Počasie ',
    'viewOnGithub': 'Zobraziť počasie Pluvia na GitHub ',
    'localTime': 'Miestny čas ',
    'loading': 'Načítava ',
    'chooseLocationToView': 'Vyberte si miesto pre zobrazenie počasia. ',
    'openLocationSettings': 'Otvorte nastavenia polohy ',
    'close': 'Zavrieť ',
    'retry': 'Skúsiť znova ',
    'serverErrorTitle': 'Chyba servera ',
    'serverErrorBody':
        'PLUVIA Počasie nemohlo získať údaje. Servery OpenWeatherMap môžu byť dole. ',
    'networkErrorText': 'Prosím, povoľte WiFi alebo mobilné údaje a opakovať ',
    'gettingLocationMessage': 'Získanie umiestnenia ... '
  },
  'sl': {
    'current': 'Tok ',
    'forecast': 'Napoved ',
    'locations': 'Lokacije ',
    'more': 'Več. ',
    'feelsLike': 'Čuti se kot ',
    'wind': 'Wind. ',
    'sunrise': 'Sunrise. ',
    'sunset': 'Sončni zahod ',
    'humidity': 'Vlažnost ',
    'pressure': 'Pritisk ',
    'currentLocationTitle': 'Trenutna lokacija ',
    'weatherRadar': 'Vreme radar. ',
    'weatherRadarAboutTitle': 'O vremenskem radarju ',
    'weatherRadarAboutBody':
        '"Vremenski radar v vremenu Pluvia" uporablja spletno stran "Openwermap". Podpira ogled padavin, tlaka, temperature, hitrosti vetra in napovedi oblaka na svetovni ravni. To lahko povzroči višjo porabo podatkov. ',
    'lastUpdatedAt': 'Nazadnje posodobljeno ',
    'locationDisabledPrompt':
        'Za vreme Pluvia, da pokažete vreme na vaši trenutni lokaciji, omogočite lokacijo. ',
    'darkMode': 'Dark način ',
    'useFahrenheit': 'Uporabite Fahrenheit. ',
    'refreshToSee': 'Osveži, da vidim spremembe ',
    'windSpeedUnit': 'Enota za hitrost vetra ',
    'aboutPluvia': 'O Pluvia vreme ',
    'viewOnGithub': 'Oglejte si vreme Pluvia na GitHub ',
    'localTime': 'Lokalni čas ',
    'loading': 'nalaganje ',
    'chooseLocationToView': 'Izberite lokacijo, da si ogledate vreme. ',
    'openLocationSettings': 'Nastavitve odprte lokacije ',
    'close': 'Zapri ',
    'retry': 'Poskusite znova ',
    'serverErrorTitle': 'Napaka strežnika ',
    'serverErrorBody':
        'Pluvia Vreme ni bilo mogoče dobiti podatkov. Strežniki Openweathap se lahko znižajo. ',
    'networkErrorText':
        'Omogočite WiFi ali mobilne podatke in poskusite znova ',
    'gettingLocationMessage': 'Pridobivanje lokacije ... '
  },
  'sq': {
    'current': 'Aktual ',
    'forecast': 'Parashikim ',
    'locations': 'Vendndodhje ',
    'more': 'Më shumë ',
    'feelsLike': 'Ndjehet si ',
    'wind': 'Era ',
    'sunrise': 'Agim ',
    'sunset': 'Muzg ',
    'humidity': 'Lagështi ',
    'pressure': 'Presion ',
    'currentLocationTitle': 'Vendndodhja aktuale ',
    'weatherRadar': 'Radar ',
    'weatherRadarAboutTitle': 'Rreth radarit të motit ',
    'weatherRadarAboutBody':
        '"Moti i motit" i Motut të PLUVI-it përdor një uebfaqe \'OpenWeATEATHERMAP\'. Mbështet duke parë reshjet, presionin, temperaturën, shpejtësinë e erës dhe parashikimet e reve në nivel global. Kjo mund të çojë në përdorim më të lartë të të dhënave. ',
    'lastUpdatedAt': 'Përditësimi i fundit në ',
    'locationDisabledPrompt':
        'Për motin e PLUVIA për të treguar motin në vendndodhjen tuaj të tanishme, aktivizoni vendndodhjen. ',
    'darkMode': 'Modaliteti i errët ',
    'useFahrenheit': 'Përdorni Fahrenheit ',
    'refreshToSee': 'Refresh për të parë ndryshimet ',
    'windSpeedUnit': 'Njësia e shpejtësisë së erës ',
    'aboutPluvia': 'Rreth Moti Plavia ',
    'viewOnGithub': 'Shiko motin e Pluvia në GitHub ',
    'localTime': 'Koha lokale ',
    'loading': 'Ngarkim ',
    'chooseLocationToView': 'Zgjidhni një vend për të parë motin. ',
    'openLocationSettings': 'Cilësimet e vendndodhjes së hapur ',
    'close': 'Mbyll ',
    'retry': 'Përsëris ',
    'serverErrorTitle': 'Gabim i serverit ',
    'serverErrorBody':
        'Moti i PLUVIA nuk mund të merrte të dhëna. Serverat e hapura mund të jenë poshtë. ',
    'networkErrorText':
        'Ju lutemi të aktivizoni të dhënat WiFi ose celular dhe të provoni përsëri ',
    'gettingLocationMessage': 'Marrja e vendndodhjes ... '
  },
  'sr': {
    'current': 'Тренутни ',
    'forecast': 'Прогноза ',
    'locations': 'Локације ',
    'more': 'Више ',
    'feelsLike': 'Осећа као ',
    'wind': 'Ветар ',
    'sunrise': 'излазак Сунца ',
    'sunset': 'залазак сунца ',
    'humidity': 'Влажност ',
    'pressure': 'Притисак ',
    'currentLocationTitle': 'Тренутна локација ',
    'weatherRadar': 'Временски радник ',
    'weatherRadarAboutTitle': 'О временском радарском радару ',
    'weatherRadarAboutBody':
        'Временски радник Плувиа Време "користи" Опенвеатхеатхермап "веб страницу. Подржава гледање падавина, притиска, температуру, брзину ветра и прогнозе у облаку широм света. То може довести до веће употребе података. ',
    'lastUpdatedAt': 'Последње ажурирано на ',
    'locationDisabledPrompt':
        'Да би се Плувиа Време приказали временске прилике на вашој тренутној локацији, Омогућите локацију. ',
    'darkMode': 'Тамни режим ',
    'useFahrenheit': 'Користите Фахренхеита ',
    'refreshToSee': 'Освежите да бисте видели промене ',
    'windSpeedUnit': 'Јединица за брзину ветра ',
    'aboutPluvia': 'О Плувиа Време ',
    'viewOnGithub': 'Погледајте Плувиа Време на Гитхуб-у ',
    'localTime': 'Локално време ',
    'loading': 'Утоваривање ',
    'chooseLocationToView': 'Изаберите локацију да бисте видели време. ',
    'openLocationSettings': 'Подешавања отворене локације ',
    'close': 'Близу ',
    'retry': 'Покушај поново ',
    'serverErrorTitle': 'грешка на серверу ',
    'serverErrorBody':
        'Плувиа Време није могло добити податке. ОпенвеатхерМап сервери могу бити доле. ',
    'networkErrorText':
        'Омогућите ВИФИ или мобилне податке и покушајте поново ',
    'gettingLocationMessage': 'Добијање локације ... '
  },
  'sv': {
    'current': 'Nuvarande ',
    'forecast': 'Prognos ',
    'locations': 'Plats ',
    'more': 'Mer ',
    'feelsLike': 'Känns som ',
    'wind': 'Vind ',
    'sunrise': 'Soluppgång ',
    'sunset': 'Solnedgång ',
    'humidity': 'Fuktighet ',
    'pressure': 'Tryck ',
    'currentLocationTitle': 'Nuvarande position ',
    'weatherRadar': 'Väderradar ',
    'weatherRadarAboutTitle': 'Om väderradar ',
    'weatherRadarAboutBody':
        "Pluvia Weather's 'Weather Radar' använder en 'OpenweathermAp' hemsida. Den stöder visning av nederbörd, tryck, temperatur, vindhastighet och molnprognoser globalt. Detta kan leda till högre dataanvändning. ",
    'lastUpdatedAt': 'Senast uppdaterad på ',
    'locationDisabledPrompt':
        'För Väder för Pluvia att visa väder i din nuvarande plats, aktivera plats. ',
    'darkMode': 'Mörkt läge ',
    'useFahrenheit': 'Använd Fahrenheit ',
    'refreshToSee': 'Uppdatera för att se ändringar ',
    'windSpeedUnit': 'Vindhastighetsenhet ',
    'aboutPluvia': 'Om pluvia väder ',
    'viewOnGithub': 'Visa Pluvia Väder på Github ',
    'localTime': 'Lokal tid ',
    'loading': 'Läser in ',
    'chooseLocationToView': 'Välj en plats för att se väder. ',
    'openLocationSettings': 'Öppna platsinställningar ',
    'close': 'Stänga ',
    'retry': 'Försök igen ',
    'serverErrorTitle': 'Serverfel ',
    'serverErrorBody':
        'Pluvia väder kunde inte få data. Openweathermap-servrarna kan vara nere. ',
    'networkErrorText':
        'Vänligen aktivera WiFi eller mobildata och försök igen ',
    'gettingLocationMessage': 'Få plats ... '
  },
  'th': {
    'current': 'ปัจจุบัน ',
    'forecast': 'พยากรณ์ ',
    'locations': 'ตำแหน่ง ',
    'more': 'มากกว่า ',
    'feelsLike': 'รู้สึกเหมือน ',
    'wind': 'ลม ',
    'sunrise': 'พระอาทิตย์ขึ้น ',
    'sunset': 'พระอาทิตย์ตกดิน ',
    'humidity': 'ความชื้น ',
    'pressure': 'ความดัน ',
    'currentLocationTitle': 'สถานที่ปัจจุบัน ',
    'weatherRadar': 'เรดาร์สภาพอากาศ ',
    'weatherRadarAboutTitle': 'เกี่ยวกับเรดาร์สภาพอากาศ ',
    'weatherRadarAboutBody':
        "'เรดาร์สภาพอากาศ' ของ Pluvia Weather ใช้เว็บเพจ 'Openweathermap' รองรับการดูปริมาณน้ำฝนความดันอุณหภูมิความเร็วลมและการคาดการณ์บนคลาวด์ทั่วโลก สิ่งนี้อาจนำไปสู่การใช้ข้อมูลที่สูงขึ้น ",
    'lastUpdatedAt': 'อัปเดตล่าสุดที่ ',
    'locationDisabledPrompt':
        'สำหรับสภาพอากาศที่ Pluvia เพื่อแสดงสภาพอากาศในตำแหน่งปัจจุบันของคุณเปิดใช้งานสถานที่ตั้ง ',
    'darkMode': 'โหมดมืด ',
    'useFahrenheit': 'ใช้ฟาเรนไฮต์ ',
    'refreshToSee': 'รีเฟรชเพื่อดูการเปลี่ยนแปลง ',
    'windSpeedUnit': 'หน่วยความเร็วลม ',
    'aboutPluvia': 'เกี่ยวกับสภาพอากาศ Pluvia ',
    'viewOnGithub': 'ดูสภาพอากาศที่ Pluvia บน GitHub ',
    'localTime': 'เวลาท้องถิ่น ',
    'loading': 'การโหลด ',
    'chooseLocationToView': 'เลือกสถานที่เพื่อดูสภาพอากาศ ',
    'openLocationSettings': 'เปิดการตั้งค่าตำแหน่ง ',
    'close': 'ปิด ',
    'retry': 'ลองอีกครั้ง ',
    'serverErrorTitle': 'เซิร์ฟเวอร์ผิดพลาด ',
    'serverErrorBody':
        'สภาพอากาศ Pluvia ไม่สามารถรับข้อมูลได้ เซิร์ฟเวอร์ Openweathermap อาจลดลง ',
    'networkErrorText': 'โปรดเปิดใช้งาน WiFi หรือข้อมูลมือถือและลองอีกครั้ง ',
    'gettingLocationMessage': 'รับตำแหน่ง ... '
  },
  'tr': {
    'current': 'Akım ',
    'forecast': 'Tahmin etmek ',
    'locations': 'Yerler ',
    'more': 'Daha ',
    'feelsLike': 'Gibi hissettiriyor ',
    'wind': 'Rüzgâr ',
    'sunrise': 'gündoğumu ',
    'sunset': 'Gün batımı ',
    'humidity': 'Nem ',
    'pressure': 'Basınç ',
    'currentLocationTitle': 'Mevcut konum ',
    'weatherRadar': 'Hava radarı ',
    'weatherRadarAboutTitle': 'Hava radarı hakkında ',
    'weatherRadarAboutBody':
        "PLUVIA Weather'in 'Hava Radarı' 'OpenWeathermap' web sayfasını kullanıyor. Küresel olarak yağış, basınç, sıcaklık, rüzgar hızı ve bulut tahminlerini görüntülemeyi destekler. Bu, daha yüksek veri kullanımına yol açabilir. ",
    'lastUpdatedAt': 'En son güncellendi ',
    'locationDisabledPrompt':
        'PLUVIA hava durumu için mevcut konumunuzda hava durumu göster, konumu etkinleştir. ',
    'darkMode': 'Karanlık mod ',
    'useFahrenheit': 'Fahrenheit kullanın ',
    'refreshToSee': 'Değişiklikleri görmek için yenileme ',
    'windSpeedUnit': 'Rüzgar Hızı Ünitesi ',
    'aboutPluvia': 'Pluvia hava durumu hakkında ',
    'viewOnGithub': "Github'daki Pluvia hava durumu ",
    'localTime': 'Yerel zaman ',
    'loading': 'Yükleniyor ',
    'chooseLocationToView': 'Hava durumu görüntülemek için bir yer seçin. ',
    'openLocationSettings': 'Konum ayarlarını aç ',
    'close': 'Kapat ',
    'retry': 'Yeniden denemek ',
    'serverErrorTitle': 'Server hatası ',
    'serverErrorBody':
        'Pluvia hava verileri alamadı. OpenWeatherMap sunucuları aşağı olabilir. ',
    'networkErrorText':
        'Lütfen wifi veya mobil verileri etkinleştirin ve yeniden deneyin ',
    'gettingLocationMessage': 'Konum almak ... '
  },
  'uk': {
    'current': 'Струм ',
    'forecast': 'Прогноз ',
    'locations': 'Розташування ',
    'more': 'Більше ',
    'feelsLike': 'Відчуває, як ',
    'wind': 'Вітер ',
    'sunrise': 'Схід сонця ',
    'sunset': 'Захід сонця ',
    'humidity': 'Вологість ',
    'pressure': 'Тиск ',
    'currentLocationTitle': 'Поточне місцезнаходження ',
    'weatherRadar': 'Погода радара ',
    'weatherRadarAboutTitle': 'Про погоду Радар ',
    'weatherRadarAboutBody':
        'Погода-Погода "Погода" використовує веб-сторінку "OpenWeaRmap". Він підтримує осадження, тиск, температуру, швидкість вітру та хмарні прогнози в усьому світі. Це може призвести до збільшення використання даних. ',
    'lastUpdatedAt': 'Останнє оновлення ',
    'locationDisabledPrompt':
        'Для Pluvia погода, щоб показати погоду у своєму поточному місці, увімкнути місцезнаходження. ',
    'darkMode': 'Темний режим ',
    'useFahrenheit': 'Використовуйте Fahrenheit ',
    'refreshToSee': 'Оновити, щоб побачити зміни ',
    'windSpeedUnit': 'Блок швидкості вітру ',
    'aboutPluvia': 'Про Пувію Погода ',
    'viewOnGithub': 'Переглянути Пувію Погода на Github ',
    'localTime': 'Місцевий час ',
    'loading': 'Навантаження ',
    'chooseLocationToView': 'Виберіть місце для перегляду погоди. ',
    'openLocationSettings': 'Відкрийте параметри розташування ',
    'close': 'Близький ',
    'retry': 'Повторити ',
    'serverErrorTitle': 'помилка серверу ',
    'serverErrorBody':
        'Пувія погода не могла отримати дані. Відкриті сервери можуть бути вниз. ',
    'networkErrorText':
        'Будь ласка, увімкніть Wi-Fi або мобільні дані та повторіть спробу ',
    'gettingLocationMessage': 'Отримання місцезнаходження ... '
  },
  'vi': {
    'current': 'Hiện hành ',
    'forecast': 'Dự báo. ',
    'locations': 'Địa điểm ',
    'more': 'Hơn ',
    'feelsLike': 'Cảm thấy như ',
    'wind': 'Gió ',
    'sunrise': 'bình Minh ',
    'sunset': 'Hoàng hôn ',
    'humidity': 'Độ ẩm ',
    'pressure': 'Sức ép ',
    'currentLocationTitle': 'Vị trí hiện tại ',
    'weatherRadar': 'Radar thời tiết ',
    'weatherRadarAboutTitle': 'Về radar thời tiết ',
    'weatherRadarAboutBody':
        '"Radar thời tiết \'thời tiết Pluvia sử dụng trang web\' OpenWeatherMap \'. Nó hỗ trợ xem lượng mưa, áp suất, nhiệt độ, tốc độ gió và đám mây dự báo trên toàn cầu. Điều này có thể dẫn đến việc sử dụng dữ liệu cao hơn. ',
    'lastUpdatedAt': 'Cập nhật lần cuối tại ',
    'locationDisabledPrompt':
        'Đối với thời tiết Pluvia để hiển thị thời tiết ở vị trí hiện tại của bạn, cho phép vị trí. ',
    'darkMode': 'Chế độ tối ',
    'useFahrenheit': 'Sử dụng Fahrenheit. ',
    'refreshToSee': 'Làm mới để xem những thay đổi ',
    'windSpeedUnit': 'Đơn vị tốc độ gió ',
    'aboutPluvia': 'Về thời tiết Pluvia ',
    'viewOnGithub': 'Xem thời tiết Pluvia trên GitHub ',
    'localTime': 'Giờ địa phương ',
    'loading': 'Đang tải ',
    'chooseLocationToView': 'Chọn một vị trí để xem thời tiết. ',
    'openLocationSettings': 'Mở cài đặt vị trí ',
    'close': 'Đóng ',
    'retry': 'Thử lại ',
    'serverErrorTitle': 'Lỗi máy chủ ',
    'serverErrorBody':
        'Thời tiết Pluvia không thể có được dữ liệu. Các máy chủ OpenWeatherMap có thể bị hỏng. ',
    'networkErrorText':
        'Vui lòng kích hoạt WiFi hoặc dữ liệu di động và thử lại ',
    'gettingLocationMessage': 'Bắt vị trí ... '
  },
  'zh': {
    'current': '当前的 ',
    'forecast': '预报 ',
    'locations': '地点 ',
    'more': '更多的 ',
    'feelsLike': '感觉像 ',
    'wind': '风 ',
    'sunrise': '日出 ',
    'sunset': '日落 ',
    'humidity': '湿度 ',
    'pressure': '压力 ',
    'currentLocationTitle': '当前位置 ',
    'weatherRadar': '天气雷达 ',
    'weatherRadarAboutTitle': '关于天气雷达 ',
    'weatherRadarAboutBody':
        'Pluvia天气的“天气雷达”使用OpenWeathermap的网页。 它支持在全球上观看降水，压力，温度，风速和云预测。 这可能导致更高的数据使用情况。 ',
    'lastUpdatedAt': '最后更新了 ',
    'locationDisabledPrompt': '对于Pluvia天气来显示当前位置的天气，使能位置。 ',
    'darkMode': '黑暗模式 ',
    'useFahrenheit': '使用华氏度 ',
    'refreshToSee': '刷新以查看更改 ',
    'windSpeedUnit': '风速单位 ',
    'aboutPluvia': '关于Pluvia天气 ',
    'viewOnGithub': '查看Pluvia天气在GitHub上 ',
    'localTime': '当地时间 ',
    'loading': '装载 ',
    'chooseLocationToView': '选择位置查看天气。 ',
    'openLocationSettings': '打开位置设置 ',
    'close': '关闭 ',
    'retry': '重试 ',
    'serverErrorTitle': '服务器错误 ',
    'serverErrorBody': 'Pluvia天气无法获取数据。 OpenWeatherMap服务器可能会关闭。 ',
    'networkErrorText': '请启用WiFi或移动数据并重试 ',
    'gettingLocationMessage': '获取位置...... '
  },
  'zu': {
    'current': '-Dlulayo ',
    'forecast': 'Inhlaziya ',
    'locations': 'Indawo ',
    'more': 'Okuningi ',
    'feelsLike': 'Uzwa sengathi ',
    'wind': 'Umoya ',
    'sunrise': 'Ukuphuma kwelanga ',
    'sunset': 'Ukushona kwelanga ',
    'humidity': 'Ukuswakama ',
    'pressure': 'Ukucindezela ',
    'currentLocationTitle': 'Indawo Indawo Yamanje ',
    'weatherRadar': 'Radar sezulu ',
    'weatherRadarAboutTitle': 'Mayelana ne-radar yesimo sezulu ',
    'weatherRadarAboutBody':
        "I-Pluvia Weather's 'sezulu radar' isebenzisa ikhasi lewebhu 'le-OpenWeathermap'. Ixhasa ukubheka kwezulu, ingcindezi, izinga lokushisa, isivinini somoya kanye nokubikezela kwamafu emhlabeni jikelele. Lokhu kungaholela ekusetshenzisweni kwedatha ephezulu. ",
    'lastUpdatedAt': 'Kugcine ukuvuselelwa ku- ',
    'locationDisabledPrompt':
        'Okwesimo sezulu sePluvia ukukhombisa isimo sezulu endaweni yakho yamanje, vumela indawo. ',
    'darkMode': 'Imodi Emnyama ',
    'useFahrenheit': 'Sebenzisa Fahrenheit ',
    'refreshToSee': 'Vuselela ukubona izinguquko ',
    'windSpeedUnit': 'Iyunithi Yesivinini Somoya ',
    'aboutPluvia': 'Mayelana nesimo sezulu sePluvia ',
    'viewOnGithub': 'Buka isimo sezulu se-pluvia ku-github ',
    'localTime': 'Isikhathi sendawo ',
    'loading': 'Iyalelamisa ',
    'chooseLocationToView': 'Khetha indawo ukubuka isimo sezulu. ',
    'openLocationSettings': 'Izilungiselelo zendawo evulekile ',
    'close': 'Ngokuminyanisa ',
    'retry': 'MuntuLALA ',
    'serverErrorTitle': 'Iphutha leseva ',
    'serverErrorBody':
        'Isimo sezulu sePluvia asikwazanga ukuthola idatha. Amaseva we-OpenWeathermap angaba phansi. ',
    'networkErrorText':
        'Sicela unike amandla idatha ye-wifi noma yeselula bese uzama futhi ',
    'gettingLocationMessage': 'Ukuthola Indawo ... '
  }
};
